version: '2'
services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zoo1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zoo1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka1:9092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka1_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka1_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    volumes:
      - ./secrets:/etc/kafka/secrets
      - ./properties:/etc/kafka/properties

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.2
    hostname: control-center
    container_name: control-center
    ports:
      - "9021:9021"
    depends_on:
      - kafka1
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_SECURITY_PROTOCOL: SSL
      CONTROL_CENTER_SECURITY_SSL_KEYSTORE_FILENAME: controlcenter.jks
      CONTROL_CENTER_SECURITY_SSL_KEYSTORE_CREDENTIALS: controlcenter_keystore_creds
      CONTROL_CENTER_SECURITY_SSL_KEY_CREDENTIALS: controlcenter_sslkey_creds
      CONTROL_CENTER_SECURITY_SSL_TRUSTSTORE_FILENAME: controlcenter.truststore.jks
      CONTROL_CENTER_SECURITY_SSL_TRUSTSTORE_CREDENTIALS: controlcenter_truststore_creds
    volumes:
      - ./control-center-secrets:/etc/confluent-control-center/secrets
